// ─── Members ────────────────────────────────────────────────────────────────
export const MEMBERS = [
  {
    id: 'user-1',
    name: 'Rushikesh',
    email: 'rushikesh@techpulse.com',
    role: 'Developer',
    department: 'Engineering',
    avatar: null,
    initials: 'RK',
    color: '#6366f1',
    tasksAssigned: 8,
    tasksCompleted: 5,
  },
  {
    id: 'user-2',
    name: 'Rahul Sharma',
    email: 'rahul@techpulse.com',
    role: 'Team Lead',
    department: 'Engineering',
    avatar: null,
    initials: 'RS',
    color: '#f59e0b',
    tasksAssigned: 12,
    tasksCompleted: 9,
  },
  {
    id: 'user-3',
    name: 'Priya Patel',
    email: 'priya@techpulse.com',
    role: 'UI/UX Designer',
    department: 'Design',
    avatar: null,
    initials: 'PP',
    color: '#ec4899',
    tasksAssigned: 6,
    tasksCompleted: 4,
  },
  {
    id: 'user-4',
    name: 'Amit Kumar',
    email: 'amit@techpulse.com',
    role: 'Developer',
    department: 'Engineering',
    avatar: null,
    initials: 'AK',
    color: '#10b981',
    tasksAssigned: 15,
    tasksCompleted: 11,
  },
  {
    id: 'user-5',
    name: 'Sneha Reddy',
    email: 'sneha@techpulse.com',
    role: 'QA Engineer',
    department: 'Quality',
    avatar: null,
    initials: 'SR',
    color: '#8b5cf6',
    tasksAssigned: 9,
    tasksCompleted: 7,
  },
  {
    id: 'user-6',
    name: 'Karan Mehta',
    email: 'karan@techpulse.com',
    role: 'Project Manager',
    department: 'Management',
    avatar: null,
    initials: 'KM',
    color: '#f97316',
    tasksAssigned: 4,
    tasksCompleted: 3,
  },
];

export const CURRENT_USER = MEMBERS[0];

// ─── Projects ────────────────────────────────────────────────────────────────
export const PROJECTS = [
  {
    id: 'proj-1',
    name: 'TechPulse CRM',
    description: 'Customer relationship management system with real-time analytics and pipeline management.',
    status: 'ACTIVE',
    color: '#6366f1',
    progress: 75,
    totalTasks: 32,
    completedTasks: 24,
    memberIds: ['user-1', 'user-2', 'user-4', 'user-5'],
    dueDate: '2026-09-30',
    createdAt: '2026-06-01',
  },
  {
    id: 'proj-2',
    name: 'E-Commerce Platform',
    description: 'Full-featured online shopping platform with payment gateway integration and inventory management.',
    status: 'ACTIVE',
    color: '#f59e0b',
    progress: 60,
    totalTasks: 24,
    completedTasks: 14,
    memberIds: ['user-1', 'user-2', 'user-3', 'user-6'],
    dueDate: '2026-10-15',
    createdAt: '2026-06-15',
  },
  {
    id: 'proj-3',
    name: 'Mobile App',
    description: 'Cross-platform mobile application for iOS and Android with offline support.',
    status: 'ACTIVE',
    color: '#10b981',
    progress: 40,
    totalTasks: 18,
    completedTasks: 7,
    memberIds: ['user-1', 'user-3', 'user-4'],
    dueDate: '2026-11-01',
    createdAt: '2026-07-01',
  },
  {
    id: 'proj-4',
    name: 'Analytics Dashboard',
    description: 'Real-time business intelligence dashboard with customizable widgets and data visualization.',
    status: 'ON_HOLD',
    color: '#ec4899',
    progress: 25,
    totalTasks: 20,
    completedTasks: 5,
    memberIds: ['user-2', 'user-3', 'user-6'],
    dueDate: '2026-12-01',
    createdAt: '2026-07-15',
  },
  {
    id: 'proj-5',
    name: 'HR Management System',
    description: 'Comprehensive HR platform for employee management, payroll, and performance tracking.',
    status: 'ACTIVE',
    color: '#8b5cf6',
    progress: 55,
    totalTasks: 28,
    completedTasks: 15,
    memberIds: ['user-2', 'user-5', 'user-6'],
    dueDate: '2026-10-30',
    createdAt: '2026-05-01',
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const TASKS = [
  {
    id: 'TASK-1001',
    title: 'Fix authentication issue',
    description: 'Users are unable to login when JWT token expires. The refresh token mechanism is not working correctly. Need to investigate and fix the token refresh logic in the auth middleware.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    reporterId: 'user-2',
    dueDate: '2026-08-25',
    createdAt: '2026-08-20',
    tags: ['auth', 'bug', 'backend'],
    comments: [
      {
        id: 'c-1',
        authorId: 'user-2',
        text: 'Can you check the refresh token logic? The expiry time might be set incorrectly.',
        createdAt: '2026-08-21T09:30:00',
      },
      {
        id: 'c-2',
        authorId: 'user-1',
        text: 'I found the issue. The token expiry is set to seconds but being compared as milliseconds. Working on the fix now.',
        createdAt: '2026-08-21T11:15:00',
      },
    ],
    activity: [
      { type: 'created', userId: 'user-1', timestamp: '2026-08-20T10:00:00', detail: 'Created this task' },
      { type: 'assigned', userId: 'user-2', timestamp: '2026-08-20T10:05:00', detail: 'Assigned to Rushikesh' },
      { type: 'status_changed', userId: 'user-1', timestamp: '2026-08-21T08:00:00', detail: 'TODO → IN_PROGRESS' },
      { type: 'priority_changed', userId: 'user-2', timestamp: '2026-08-21T09:00:00', detail: 'MEDIUM → HIGH' },
    ],
  },
  {
    id: 'TASK-1002',
    title: 'Implement payment gateway',
    description: 'Integrate Razorpay payment gateway into the E-Commerce platform. Should support credit/debit cards, UPI, and net banking. Implement webhook handlers for payment confirmation.',
    status: 'TODO',
    priority: 'URGENT',
    projectId: 'proj-2',
    assigneeId: 'user-1',
    reporterId: 'user-6',
    dueDate: '2026-08-26',
    createdAt: '2026-08-18',
    tags: ['payment', 'integration', 'backend'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-18T14:00:00', detail: 'Created this task' },
      { type: 'assigned', userId: 'user-6', timestamp: '2026-08-18T14:05:00', detail: 'Assigned to Rushikesh' },
    ],
  },
  {
    id: 'TASK-1003',
    title: 'Design dashboard UI',
    description: 'Create responsive dashboard layouts for the Analytics Dashboard project. Include charts, KPI widgets, and a customizable grid layout system.',
    status: 'IN_REVIEW',
    priority: 'MEDIUM',
    projectId: 'proj-4',
    assigneeId: 'user-3',
    reporterId: 'user-2',
    dueDate: '2026-08-28',
    createdAt: '2026-08-15',
    tags: ['ui', 'design', 'dashboard'],
    comments: [
      {
        id: 'c-3',
        authorId: 'user-2',
        text: 'The designs look great! Just need to adjust the mobile breakpoints and then we can merge.',
        createdAt: '2026-08-27T10:00:00',
      },
    ],
    activity: [
      { type: 'created', userId: 'user-3', timestamp: '2026-08-15T09:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-3', timestamp: '2026-08-20T14:00:00', detail: 'TODO → IN_PROGRESS' },
      { type: 'status_changed', userId: 'user-3', timestamp: '2026-08-27T09:00:00', detail: 'IN_PROGRESS → IN_REVIEW' },
    ],
  },
  {
    id: 'TASK-1004',
    title: 'API integration testing',
    description: 'Write comprehensive test suites for all REST API endpoints. Cover happy paths, error cases, and edge cases. Target 80% code coverage.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    projectId: 'proj-3',
    assigneeId: 'user-5',
    reporterId: 'user-2',
    dueDate: '2026-08-30',
    createdAt: '2026-08-16',
    tags: ['testing', 'api', 'qa'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-2', timestamp: '2026-08-16T11:00:00', detail: 'Created this task' },
      { type: 'assigned', userId: 'user-2', timestamp: '2026-08-16T11:05:00', detail: 'Assigned to Sneha Reddy' },
      { type: 'status_changed', userId: 'user-5', timestamp: '2026-08-19T09:00:00', detail: 'TODO → IN_PROGRESS' },
    ],
  },
  {
    id: 'TASK-1005',
    title: 'Update documentation',
    description: 'Update the API documentation in Swagger/OpenAPI format. Include all new endpoints added in the v2 release. Add request/response examples.',
    status: 'TODO',
    priority: 'LOW',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    reporterId: 'user-2',
    dueDate: '2026-09-02',
    createdAt: '2026-08-22',
    tags: ['docs', 'api'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-2', timestamp: '2026-08-22T15:00:00', detail: 'Created this task' },
      { type: 'assigned', userId: 'user-2', timestamp: '2026-08-22T15:05:00', detail: 'Assigned to Rushikesh' },
    ],
  },
  {
    id: 'TASK-1006',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions workflow for automated build, test, and deployment pipeline. Include staging and production environments.',
    status: 'COMPLETED',
    priority: 'HIGH',
    projectId: 'proj-1',
    assigneeId: 'user-4',
    reporterId: 'user-6',
    dueDate: '2026-08-15',
    createdAt: '2026-08-10',
    tags: ['devops', 'ci-cd'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-10T09:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-4', timestamp: '2026-08-14T16:00:00', detail: 'IN_PROGRESS → COMPLETED' },
    ],
  },
  {
    id: 'TASK-1007',
    title: 'Database schema optimization',
    description: 'Analyze slow queries and optimize database schema. Add necessary indexes and consider query caching for frequently accessed data.',
    status: 'BLOCKED',
    priority: 'URGENT',
    projectId: 'proj-1',
    assigneeId: 'user-4',
    reporterId: 'user-2',
    dueDate: '2026-08-20',
    createdAt: '2026-08-12',
    tags: ['database', 'performance', 'backend'],
    comments: [
      {
        id: 'c-4',
        authorId: 'user-4',
        text: 'Blocked on access to the production database credentials. Need DBA approval.',
        createdAt: '2026-08-18T14:00:00',
      },
    ],
    activity: [
      { type: 'created', userId: 'user-2', timestamp: '2026-08-12T10:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-4', timestamp: '2026-08-14T09:00:00', detail: 'TODO → IN_PROGRESS' },
      { type: 'status_changed', userId: 'user-4', timestamp: '2026-08-18T14:00:00', detail: 'IN_PROGRESS → BLOCKED' },
    ],
  },
  {
    id: 'TASK-1008',
    title: 'Mobile push notifications',
    description: 'Implement Firebase Cloud Messaging for push notifications on the mobile app. Handle foreground, background, and terminated states.',
    status: 'TODO',
    priority: 'MEDIUM',
    projectId: 'proj-3',
    assigneeId: 'user-1',
    reporterId: 'user-6',
    dueDate: '2026-09-10',
    createdAt: '2026-08-23',
    tags: ['mobile', 'notifications', 'firebase'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-23T11:00:00', detail: 'Created this task' },
    ],
  },
  {
    id: 'TASK-1009',
    title: 'User onboarding flow',
    description: 'Design and implement a guided onboarding flow for new users. Include welcome screens, feature highlights, and initial setup wizard.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    projectId: 'proj-2',
    assigneeId: 'user-3',
    reporterId: 'user-6',
    dueDate: '2026-09-05',
    createdAt: '2026-08-19',
    tags: ['ux', 'onboarding', 'frontend'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-19T13:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-3', timestamp: '2026-08-22T09:00:00', detail: 'TODO → IN_PROGRESS' },
    ],
  },
  {
    id: 'TASK-1010',
    title: 'Performance audit & optimization',
    description: 'Conduct a full Lighthouse audit and optimize Core Web Vitals. Target 90+ performance score on mobile and desktop.',
    status: 'COMPLETED',
    priority: 'HIGH',
    projectId: 'proj-2',
    assigneeId: 'user-1',
    reporterId: 'user-2',
    dueDate: '2026-08-22',
    createdAt: '2026-08-10',
    tags: ['performance', 'frontend'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-2', timestamp: '2026-08-10T10:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-1', timestamp: '2026-08-22T17:00:00', detail: 'IN_PROGRESS → COMPLETED' },
    ],
  },
  {
    id: 'TASK-1011',
    title: 'Inventory management module',
    description: 'Build inventory tracking module with stock alerts, reorder points, and supplier management.',
    status: 'TODO',
    priority: 'HIGH',
    projectId: 'proj-2',
    assigneeId: 'user-4',
    reporterId: 'user-6',
    dueDate: '2026-09-15',
    createdAt: '2026-08-24',
    tags: ['inventory', 'backend', 'feature'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-24T10:00:00', detail: 'Created this task' },
    ],
  },
  {
    id: 'TASK-1012',
    title: 'Employee leave management',
    description: 'Implement leave request, approval workflow, and leave balance tracking for the HR system.',
    status: 'IN_REVIEW',
    priority: 'MEDIUM',
    projectId: 'proj-5',
    assigneeId: 'user-5',
    reporterId: 'user-6',
    dueDate: '2026-09-01',
    createdAt: '2026-08-17',
    tags: ['hr', 'workflow', 'backend'],
    comments: [],
    activity: [
      { type: 'created', userId: 'user-6', timestamp: '2026-08-17T09:00:00', detail: 'Created this task' },
      { type: 'status_changed', userId: 'user-5', timestamp: '2026-08-25T14:00:00', detail: 'IN_PROGRESS → IN_REVIEW' },
    ],
  },
];

// ─── Notifications ───────────────────────────────────────────────────────────
export const NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'task_assigned',
    message: 'Rahul Sharma assigned TASK-1002 to you',
    taskId: 'TASK-1002',
    userId: 'user-2',
    isRead: false,
    createdAt: '2026-08-27T10:35:00',
  },
  {
    id: 'notif-2',
    type: 'comment',
    message: 'Priya Patel commented on TASK-1003',
    taskId: 'TASK-1003',
    userId: 'user-3',
    isRead: false,
    createdAt: '2026-08-27T10:12:00',
  },
  {
    id: 'notif-3',
    type: 'status_changed',
    message: 'Task "Design dashboard UI" moved to In Review',
    taskId: 'TASK-1003',
    userId: 'user-3',
    isRead: false,
    createdAt: '2026-08-27T09:00:00',
  },
  {
    id: 'notif-4',
    type: 'task_completed',
    message: 'Amit Kumar completed TASK-1006',
    taskId: 'TASK-1006',
    userId: 'user-4',
    isRead: false,
    createdAt: '2026-08-26T16:00:00',
  },
  {
    id: 'notif-5',
    type: 'deadline_reminder',
    message: 'TASK-1001 deadline is tomorrow',
    taskId: 'TASK-1001',
    userId: null,
    isRead: true,
    createdAt: '2026-08-24T09:00:00',
  },
  {
    id: 'notif-6',
    type: 'project_milestone',
    message: 'Project TechPulse CRM reached 75% completion',
    taskId: null,
    projectId: 'proj-1',
    userId: null,
    isRead: true,
    createdAt: '2026-08-23T14:00:00',
  },
];

// ─── Report Data ─────────────────────────────────────────────────────────────
export const COMPLETION_TREND = [
  { date: 'Aug 1', completed: 2 },
  { date: 'Aug 5', completed: 5 },
  { date: 'Aug 10', completed: 8 },
  { date: 'Aug 15', completed: 11 },
  { date: 'Aug 20', completed: 15 },
  { date: 'Aug 25', completed: 18 },
  { date: 'Aug 27', completed: 20 },
];
